Add Code coverage badge to the repo
adamghill/django-unicorn pull request #695
Opened 2024-06-21 17:00 UTC by mihrab34

to fix #692 

![django-unicorn – README md 6_21_2024 4_57_51 PM](https://github.com/adamghill/django-unicorn/assets/35562131/e44983cd-e2f2-4a36-b4cb-34131451c235)

2024-06-21 17:00 UTC, mihrab34 commented
@adamghill

2024-06-21 17:02 UTC, mihrab34 commented
I also generated the coverage report in HTML, in case you would like to look at it later.

2024-06-21 20:53 UTC, adamghill commented
Thank you! This looks great! I assume this would require manually running `genbadge` and committing the output? Should that be added to docs somewhere? Maybe the new CONTRIBUTING.md file I am going to make?

Did you see any way to automate updating a README.md with a calculated badge on every merge into `main`? I found https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa (which looks like a real hack) and https://github.com/marketplace/actions/pytest-coverage-comment#auto-updating-badge-on-readme (which maybe isn't as bad)?

2024-06-22 13:52 UTC, mihrab34 commented
> Thank you! This looks great! I assume this would require manually running `genbadge` and committing the output? Should that be added to docs somewhere? Maybe the new CONTRIBUTING.md file I am going to make?
> 
> Did you see any way to automate updating a README.md with a calculated badge on every merge into `main`? I found https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa (which looks like a real hack) and https://github.com/marketplace/actions/pytest-coverage-comment#auto-updating-badge-on-readme (which maybe isn't as bad)?

I did read something about running the whole process with GitHub actions. I'd look at the links you shared and add that to the implementation. Thanks!

2024-06-24 12:52 UTC, mihrab34 commented
@adamghill Instead of using GitHub gist, I added the last step in the workflow as a commit process, as I wanted to keep all the badging processes within the repository.

2024-06-24 12:56 UTC, adamghill commented
Makes sense! Yeah the gist process seemed pretty strange. I'll take a look in detail soon, thank you!

2024-06-24 22:03 UTC, adamghill commented
It's a bummer there needs to be a commit just for updating the coverage number in the readme, but it looks like https://github.com/MishaKav/pytest-coverage-comment/blob/main/.github/workflows/update-coverage-on-readme.yml does basically the same thing. 🤷 Maybe no good way around it.

This looks great! Thanks for setting it all up. 🚀

2024-06-24 22:05 UTC, adamghill commented on .github/workflows/coverage.yml
> +on: [push]
I think we should only run this on push to `main`. What do you think? https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters

2024-06-24 22:11 UTC, adamghill requested changes
This looks good, I think we should only run it for pushes to `main`, but other than that I think it can be merged in!

2024-06-25 10:30 UTC, mihrab34 commented
@adamghill updated to run only on push to `main`

2024-06-26 11:25 UTC, adamghill approved these changes
🚀

2024-06-26 11:26 UTC, merged

2024-07-05 12:09 UTC, adamghill commented
@all-contributors add mihrab34 for code