Set up Issue template
adamghill/django-unicorn pull request #700
Opened 2024-06-27 15:58 UTC by mihrab34

to close #694

2024-06-27 16:24 UTC, mihrab34 commented
@adamghill I have some commits from my `origin main branch`. My local branch is up to date with the upstream and origin. Is there a way I could clean the commit history up? I'm thinking `git rebase`

2024-06-28 02:51 UTC, adamghill commented
Yes! I think a rebase and force push should do it. If it doesn't work we can take a look at it tomorrow. 👍

2024-07-02 12:04 UTC, mihrab34 commented
@adamghill

2024-07-02 13:03 UTC, adamghill commented on pyproject.toml
> +<<<<<<< HEAD
I think you might have some merge conflicts still in here?

2024-07-02 13:04 UTC, adamghill commented on .github/workflows/coverage.yml
Is this from the other PR? Maybe a rebase will clear this out?

2024-07-02 13:05 UTC, adamghill requested changes
The issue templates look great! If you can clear out the extraneous commits that would be awesome, otherwise I might be able to clean them up. Let me know!

2024-07-03 07:52 UTC, mihrab34 commented on .github/workflows/coverage.yml
yes, got that after merging my `origin main` with my current feature branch. Had to clean it up with rebase

2024-07-03 08:01 UTC, mihrab34 commented
> The issue templates look great! If you can clear out the extraneous commits that would be awesome, otherwise I might be able to clean them up. Let me know!

@adamghill  I squashed all of them into 1 and fixed the part with the merge conflict.

2024-07-03 13:15 UTC, adamghill approved these changes
🚀

2024-07-03 13:15 UTC, merged